- name: 📂 Sync files with FTP
  uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  with:
    server: ftp.emmanueliykefoundation.org
    username: ${{ secrets.ftp_username }}
    password: ${{ secrets.ftp_password }}
    protocol: ftps
    port: 21
    local-dir: './'
    timeout: 120000 # Set timeout to 120 seconds (2 minutes)
